---
background_opacity: 0.8
colors:
  bright:
    black: "0x002b36"
    blue: "0x839496"
    cyan: "0x93a1a1"
    green: "0x586e75"
    magenta: "0x6c71c4"
    red: "0xcb4b16"
    white: "0xfdf6e3"
    yellow: "0x657b83"
  normal:
    black: "0x073642"
    blue: "0x268bd2"
    cyan: "0x2aa198"
    green: "0x859900"
    magenta: "0xd33682"
    red: "0xdc322f"
    white: "0xeee8d5"
    yellow: "0xb58900"
  primary:
    background: "0x002b36"
    foreground: "0x839496"
cursor:
  style: Block
  unfocused_hollow: true
dynamic_title: true
font:
  bold:
    family: "DejaVuSansMono Nerd Font"
    style: Bold
  bold_italic:
    family: "DejaVuSansMono Nerd Font"
    style: "Bold Oblique"
  italic:
    family: "DejaVuSansMono Nerd Font"
    style: Oblique
  normal:
    family: "DejaVuSansMono Nerd Font"
    style: Book
  size: 11
key_bindings:
  -
    action: ResetFontSize
    key: Numpad0
    mods: Control
  -
    action: IncreaseFontSize
    key: NumpadAdd
    mods: Control
  -
    action: DecreaseFontSize
    key: NumpadSubtract
    mods: Control
live_config_reload: true
mouse_bindings:
  -
    action: PasteSelection
    mouse: Middle
tabspaces: 4
